### ISSUE TITLE
GET https://cosmos-chain.directory/chains => Connection timed out

### ISSUE THREAD

**Issue by kopeboy** [empowerchain/cosmos-chain-directory#2]
Need to re-deploy?
What's the plan to maintain this?

**Comment by lex51** [comment]
same problem..

**Comment by gjermundgaraba** [comment]
There is a much richer and better maintained API I would recommend using: https://github.com/eco-stake/cosmos-directory

It has all of the same things, and more. Let me know if this solves your problem, and if it doesn't I will see what I can do about getting this up to snuff! :)

**Comment by kopeboy** [comment]
Yep, thank you.
